import { createApp } from "vue";
import "@fontsource/outfit/400.css";
import "@fontsource/outfit/500.css";
import "@fontsource/outfit/600.css";
import "@fontsource/outfit/700.css";
import "@fontsource/outfit/800.css";
import "./style.css";
import "./mosh.css";
import App from "./App.vue";
createApp(App).mount("#app");
