#!/usr/bin/env python3
"""Validate the immutable v1 editorial snapshot and reproduce its Flyway seed."""
import argparse
import collections
import hashlib
import json
import re
from decimal import Decimal
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'content/catalog/v1'
TARGET = ROOT / 'quizmosh-server/src/main/resources/db/migration/V3__seed_question_catalog.sql'
LANGUAGES = ('pt-BR', 'en')


def load_questions(language):
    return json.loads((SOURCE / f'questions.{language}.json').read_text(encoding='utf-8'))


def require(condition, message):
    if not condition:
        raise ValueError(message)


def validate():
    categories = json.loads((SOURCE / 'categories.json').read_text(encoding='utf-8'))
    ids = [c['id'] for c in categories]
    require(len(ids) == len(set(ids)), 'Duplicate category')
    for c in categories:
        require(re.fullmatch(r'[a-z][a-z0-9-]{0,79}', c['id']), f'Invalid category: {c}')
        require(c['id'] != 'all', 'all is reserved for the combined category')
        require(set(c['names']) == set(LANGUAGES) and all(c['names'].values()), f'Missing category translation: {c}')
    banks = {lang: load_questions(lang) for lang in LANGUAGES}
    indexed = {}
    for lang, questions in banks.items():
        indexed[lang] = {q['id']: q for q in questions}
        require(len(indexed[lang]) == len(questions), f'Duplicate IDs: {lang}')
        seen = set()
        for q in questions:
            ident = f"{lang}/{q['id']}"
            require(re.fullmatch(r'[a-z][a-z0-9-]{0,79}', q['id']), f'Invalid ID: {ident}')
            require(q['category'] in ids, f'Unknown category: {ident}')
            require(q.get('regions') in ([], ['BR']), f'Invalid region: {ident}')
            require(all(isinstance(q.get(k), str) and q[k].strip() for k in ('prompt', 'explanation')), f'Missing text: {ident}')
            kind = q['type']
            require(kind in ('choice', 'guess', 'numeric'), f'Unknown type: {ident}')
            if kind == 'choice':
                require(len(q['options']) == 4 and len(set(q['options'])) == 4 and all(q['options']), f'Invalid options: {ident}')
                require(type(q['correctIndex']) is int and 0 <= q['correctIndex'] < 4, f'Invalid answer: {ident}')
                signature = (q['category'], kind, q['prompt'].strip().casefold())
            elif kind == 'guess':
                require(len(q['clues']) == 4 and len(set(q['clues'])) == 4 and all(q['clues']), f'Invalid clues: {ident}')
                require(q['answers'] and all(a.strip() for a in q['answers']), f'Missing aliases: {ident}')
                signature = (q['category'], kind, tuple(q['clues']))
            else:
                value = Decimal(str(q['value']))
                require(value.is_finite() and abs(value) < Decimal('1e18') and value == value.quantize(Decimal('0.000001')), f'Invalid numeric answer: {ident}')
                require(isinstance(q['unit'], str) and q['unit'].strip(), f'Missing unit: {ident}')
                signature = (q['category'], kind, q['prompt'].strip().casefold())
            require(signature not in seen, f'Duplicate question: {ident}')
            seen.add(signature)
    require(indexed['pt-BR'].keys() == indexed['en'].keys(), 'Translation IDs differ')
    for ident, pt in indexed['pt-BR'].items():
        en = indexed['en'][ident]
        for key in ('category', 'type', 'regions', 'correctIndex', 'value'):
            require(pt.get(key) == en.get(key), f'Translated semantics changed: {ident}/{key}')
    counts = collections.Counter(q['category'] for q in banks['pt-BR'])
    for category in ids:
        require(counts[category] >= 100, f'{category}: fewer than 100 canonical questions')
        for kind in ('choice', 'guess', 'numeric'):
            require(sum(q['category'] == category and q['type'] == kind and not q['regions'] for q in banks['pt-BR']) >= 12,
                    f'{category}/{kind}: fewer than 12 global questions for a full single-mode game')
    return categories, indexed, counts


def sql(value):
    if value is None:
        return 'NULL'
    if isinstance(value, (int, float, Decimal)):
        return str(value)
    if isinstance(value, list):
        value = json.dumps(value, ensure_ascii=False, separators=(',', ':'))
    return "'" + str(value).replace("'", "''") + "'"


def render(categories, banks):
    digest = hashlib.sha256(b''.join((SOURCE / f).read_bytes() for f in ('categories.json', 'questions.pt-BR.json', 'questions.en.json'))).hexdigest()
    lines = ['-- Generated by python3 scripts/catalog.py; immutable after release.',
             '-- Editorial snapshot: content/catalog/v1; SHA-256: ' + digest,
             '-- Flyway applies this seed once, also on upgrades of existing volumes.', '']
    def insert(table, columns, values):
        lines.append(f"INSERT INTO {table} ({', '.join(columns)}) VALUES ({', '.join(sql(v) for v in values)});")
    for order, category in enumerate(categories, 1):
        insert('quiz_categories', ['id', 'sort_order'], [category['id'], order])
        for lang in LANGUAGES:
            insert('quiz_category_texts', ['category_id', 'language', 'name'], [category['id'], lang, category['names'][lang]])
    for category in categories:
        lines.extend(['', '-- ' + category['names']['pt-BR']])
        for q in banks['pt-BR'].values():
            if q['category'] != category['id']:
                continue
            insert('quiz_questions', ['id', 'category_id', 'question_type', 'correct_index', 'numeric_value'],
                   [q['id'], q['category'], q['type'], q.get('correctIndex'), q.get('value')])
            for region in q['regions']:
                insert('quiz_question_regions', ['question_id', 'region'], [q['id'], region])
            for lang in LANGUAGES:
                tr = banks[lang][q['id']]
                insert('quiz_question_texts', ['question_id', 'language', 'prompt', 'explanation', 'options_json', 'clues_json', 'answers_json', 'unit'],
                       [q['id'], lang, tr['prompt'], tr['explanation'], tr.get('options'), tr.get('clues'), tr.get('answers'), tr.get('unit')])
    return '\n'.join(lines) + '\n'


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='Fail if the checked-in seed differs; do not write files')
    args = parser.parse_args()
    categories, banks, counts = validate()
    generated = render(categories, banks)
    if args.check:
        require(TARGET.exists() and TARGET.read_text(encoding='utf-8') == generated, 'Seed is out of sync; run python3 scripts/catalog.py before the first release')
    else:
        TARGET.write_text(generated, encoding='utf-8')
    print(f"Validated {sum(counts.values())} canonical questions, {len(LANGUAGES)} languages: " + ', '.join(f'{k}={v}' for k, v in counts.items()))


if __name__ == '__main__':
    main()
